name: research-project
channels:
  - defaults
dependencies:
  - python=3.12.7
  - torchvision
  - scikit-learn
  - pytorch::pytorch
  - torchaudio
  - numpy
  - transformers
  - matplotlib
  - accelerate
  - hydra-core
prefix: /Users/uni/opt/anaconda3/envs/research-project
