name: research-project
channels:
  - conda-forge
  - defaults
  - anaconda
  - nvidia
  - pytorch
dependencies:
  - python>=3.9
  - numpy<1.23.0
  - typing_extensions
  - tqdm
  - hydra-core
  - pandas
  - scikit-learn
  - matplotlib
  - nltk
  - huggingface_hub
  - pyarrow
  - ffmpeg
  - openblas-devel
  - pip
  - pytorch=2.5.1=py3.12_cuda11.8_cudnn9.1.0_0
  - torchaudio==2.5.1
  - torchvision==0.20.1
  - cudatoolkit=11.8
  - pip:
      - transformers
      - datasets
      - accelerate>=0.26.0
      - scipy==1.8.0
      - seaborn==0.13.0
      - prettytable
