name: research-project
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - accelerate
  - matplotlib
  - numpy
  - python
  - pytorch::pytorch
  - scikit-learn
  - torchaudio
  - torchvision
  - transformers
  - hydra-core
  - libtiff
prefix: /opt/miniconda3/envs/research-project
