name: research-project
channels:
  - conda-forge
  - defaults
  - anaconda
  - nvidia
  - pytorch
dependencies:
  - python>=3.9
  - numpy<1.23.0
  - typing_extensions
  - tqdm
  - hydra-core
  - pandas
  - scikit-learn
  - matplotlib
  - nltk
  - huggingface_hub
  - pyarrow
  - ffmpeg
  - openblas-devel
  - pip
  - pytorch=1.11.0
  - torchvision=0.12
  - torchaudio=0.11
  - cudatoolkit=11.5
  - pip:
      - transformers
      - datasets
      - accelerate>=0.26.0
      - scipy==1.8.0
      - seaborn==0.13.0
      - prettytable
