defaults:
  # running this script will pull the prompt in this file over the prompt in baseline_config file
  - SD_config
  - _self_

teacher:
  name: "meta-llama/Meta-Llama-3-70B-Instruct"
  max_new_tokens: 30
  k: 15

student:
  max_new_tokens: 30

data:
  # small data with validation
  path: "${oc.env:HOME}/tasks_1-20_v1-2/en-valid/"
  # Order: train, valid, test
  splits:
    train: False
    valid: False
    test: True
  # to get all tasks use ~ (will be converted to None)
  # to get specific tasks use:
  # task_ids: [1, 2, ...]
  task_ids: ~
  # to get all samples use ~ (will be converted to None)
  # to set a specific number of samples use an int
  samples_per_task: 100

init_prompt:
  paths:
    - "${oc.env:HOME}/research-project/inference/prompts/init_prompt_reasoning.txt"

hydra:
  run:
    # the run directory with logs, plots, and csv results will be created here
    # use more folders if needed for distinguishing between different experiments
    dir: "${oc.env:HOME}/research-project/results/speculative_decoding/test/${now:%d-%m-%Y}/${now:%H-%M-%S}"
