teacher:
  name: "meta-llama/Meta-Llama-3-8B-Instruct"
  max_new_tokens: 100
  temperature: 0.2
  to_continue: false

student:
  name: "meta-llama/Meta-Llama-3-8B-Instruct"
  max_new_tokens: 200
  temperature: 0.2
  to_continue: false

setting:
  name: 'SD'
  interpretability: True

data:
  # small data with validation
  path: '${oc.env:HOME}/tasks_1-20_v1-2/en-valid/'
  # Order: train, valid, test
  splits:
    train: False
    valid: True
    test: False
  # to get all tasks use (will be converted to None)
  task_ids: ~
  # to get specific tasks use:
  # task_ids: [1, 2, ...]
  samples_per_task: 5
  # if to add line numbers to the sentences in the prompt
  # Order: context, question
  to_enumerate:
    context: True
    question: False
  wrapper:
    # if to wrap the part prompt with the task description
    context: |
      Here are the context sentences:
      {context}
    question: |
      Now, answer the following question:
      {question}
    reasoning: ""
    answer: ""

init_prompt:
  # name of the prompt files serves as a basis for logging and result files
  paths:
    - "${oc.env:HOME}/research-project/inference/prompts/init_prompt_reasoning.txt"
  examples:
    add: True
    enumerated: True
    handpicked: True
    not_mentioned: True
    number: 1
    wrapper: |
      *EXAMPLE{number}*
      {example}

eval_prompt:
  # name of the prompt files serves as a basis for logging and result files
  paths:
    - "${oc.env:HOME}/research-project/inference/prompts/eval_prompt.txt"
  wrapper: | # if to wrap the part prompt with the task description
    The student's response was:
    {student_output}

resume_prompt:
  # name of the prompt files serves as a basis for logging and result files
  paths:
    - "${oc.env:HOME}/research-project/inference/prompts/resume_prompt.txt"
  wrapper: "{to_continue}"

logging:
  # if to print the results to a log file, otherwise will print to console
  print_to_file: True

results:
  save_heatmaps: False
  headers:
    - id
    - task_id
    - sample_id
    - part_id
    - task
    - golden_answer
    - model_answer
    - correct
    - model_reasoning
    - silver_reasoning
    - model_output
    - exact_match_accuracy
    - soft_match_accuracy
    - there
    - verbs
    - pronouns
    - not_mentioned

hydra:
  run:
    # the run directory with logs, plots, and csv results will be created here
    # use more folders if needed for distinguishing between different experiments
    dir: "${oc.env:HOME}/research-project/outputs/${now:%d-%m-%Y}/${now:%H-%M-%S}"
