defaults:
  # running this script will pull the prompt in this file over the prompt in baseline_config file
  - feedback_config
  - _self_

init_prompt:
  # name of the prompt files serves as a basis for logging and result files
  paths:
    - "${oc.env:HOME}/research-project/inference/prompts/init_prompt_reasoning.txt"

feedback_prompt:
  # name of the prompt files serves as a basis for logging and result files
  paths:
    - "${oc.env:HOME}/research-project/inference/prompts/feedback_prompt.txt"

refine_prompt:
  # name of the prompt files serves as a basis for logging and result files
  paths:
    - "${oc.env:HOME}/research-project/inference/prompts/refine_prompt.txt"

hydra:
  run:
    # the run directory with logs, plots, and csv results will be created here
    # use more folders if needed for distinguishing between different experiments
    dir: "/pfs/work9/workspace/scratch/hd_mr338-research-results-2/feedback/${now:%d-%m-%Y}/${now:%H-%M-%S}"
