defaults:
  # running this script will pull the prompt in this file over the prompt in baseline_config file
  - baseline_config
  - _self_

model:
  max_new_tokens: 300

data:
  path: "${oc.env:HOME}/tasks_1-20_v1-2/en-valid/"
  task_ids: ~
  samples_per_task: 100
  start_from_sample: 0
  for_all_tasks: false # whether to start from a specific sample for all tasks (will start from 0 otherwise)
  splits:
    train: False
    valid: False
    test: True

init_prompt:
  paths:
    - "${oc.env:HOME}/research-project/inference/prompts/init_prompt_reasoning.txt"

logging:
  # if to print the results to a log file, otherwise will print to console
  print_to_file: True

hydra:
  run:
    # the run directory with logs, plots, and csv results will be created here
    # use more folders if needed for distinguishing between different experiments
    dir: "/pfs/work9/workspace/scratch/hd_nc326-research-project/baseline/test/reasoning/${now:%d-%m-%Y}/${now:%H-%M-%S}"
