defaults:
  # running this script will pull the prompt in this file over the prompt in baseline_config file
  - baseline_config
  - _self_

init_prompt:
  paths:
    - "where/ever/the/prompts/will/be"

hydra:
  run:
    # the run directory with logs, plots, and csv results will be created here
    # use more folders if needed for distinguishing between different experiments
    dir: "/pfs/work9/workspace/scratch/hd_mr338-research-results-2/baseline/${now:%d-%m-%Y}/${now:%H-%M-%S}"
